### PR TITLE
gmail support, multiple vcards in .vcf file

### PR DESCRIPTION
**Pull request by AngelKyriako**
Gmail exports your contacts into csv or vcf files.
https://support.google.com/mail/answer/1069522?hl=en (export & backup section)

In case of vcf it will generate one file with multiple vcard entries. This update supports this and returns an array of vCard objects with the callback. when a single vcard is returned, it will return the single element for compatibility with the previous versions.

I could not find a way to run the automated tests in the spec directory. Let me know, if you are going to merge this or I should create a new npm module for this.

cheers

Example file:

BEGIN:VCARD
VERSION:3.0
FN:<test>
N:;<test>;;;
EMAIL;TYPE=INTERNET:test@gmail.com
END:VCARD
BEGIN:VCARD
VERSION:3.0
FN:test2
N:test2;;;
EMAIL;TYPE=INTERNET:test2@gmail.com
END:VCARD

### CODE REVIEW

**Comment by AngelKyriako** [comment]
@jasperla If you prefer a better implementation of the feature, let me know your preferences.

**Comment by jasperla** [comment]
This is great, I'll review it shortly!

**Comment by AngelKyriako** [comment]
@jasperla how is the review going ?

I will need it quite soon for a live app.
In case you do not have time , I could upload a temp npm module on the registry

**Comment by jasperla** [comment]
Thanks, it's merged and released as 0.1.0.

Could you submit a separate PR for adding tests though?

**Comment by AngelKyriako** [comment]
thanks a lot captain,

cheers

**Pull request merged**
